name: Trigger auto deployment for rag-resume-app

on:
  push:
    branches: 
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RAGRESUMEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RAGRESUMEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RAGRESUMEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        # CHANGED: Using @v1 for stability
        uses: azure/container-apps-build-and-deploy@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          
          # Your Manual Secrets
          registryUrl: ${{ secrets.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
          registryUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          
          # App Details
          containerAppName: rag-resume-app
          resourceGroup: rag-demo-rg
          imageToBuild: rag-resume-app:${{ github.sha }}
          dockerfilePath: Dockerfile
